#!/usr/bin/env bash
# displays 'To infinity and beyond' infinitely, until it the process recieves a
# SIGTERM signal

while true; do
    trap "echo I am invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done

