#!/usr/bin/env bash
#script that loops from 1 to 10 
COUNT=1
while [ $COUNT -lt 11 ]
do
    if [ $COUNT -eq 4 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
    let COUNT=$COUNT+1
done