#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
min=1
hour=0
while [ $hour -lt 13 ]
do
	let min=1
	echo "Hour: $hour"
	while [ $min -lt 60 ]
	do
		echo "$min"
		let min=min+1
	done
	let hour=hour+1
done